site_name: Contributing to Datapunt
pages:
    - Introduction: 'index.md'
    - Projects: 'projects.md'
    - Python: 'python.md'
    - Code: 'code.md'
    - Self: 'self.md'
site_url: http:///contributing/
repo_url: https://github.com/DatapuntAmsterdam/style-guide/
site_favicon: favicon.png
theme: readthedocs
